* RenderTones
TP 2024-05-19

* Objective
Play sounds

* Background
The RationalMusic.play function no longer works.

However, this simple demo does:


julia> using PortAudio, SampledSignals
julia> S = 44100 ## 8192 # sampling rate (samples / second)
julia> x = cos.(2pi*(1:2S)*440/S) # A440 tone for 2 seconds
julia> PortAudioStream("pulse", "pulse", 0, 2; samplerate=S) do stream
       # PortAudioStream(0, 2; samplerate=S) do stream
           write(stream, x)
       end
88200

* Start pkg
julia> Pkg.generate("RenderTones")
tp@ace7900:~/github/tp2750/Blog/en/2024/2024-05-19_RenderTones/RenderTones$ julia --project=.

* Problems with PortAudio
When using PortAudio from a package (like RationalMusic etc) it looks like it recompiles, and that fails.
I'm not alone: https://github.com/JuliaAudio/PortAudio.jl/issues/126
Maintanier says:
he problem doesn't appear to be finding libasound_module_pcm_a52.so, it's that that library seems to be dependent on libavcodec.so.58, which it's not finding.
what version of alsa_jll, alsa_plugins_jll, libportaudio_jll, and FFMPEG_jll do you have installed? In particular, that libasound module is provided by alsa_plugins_jll, and the libavcodec should be provided by FFMPEG_jll.
It looks like the latest version of FFMPEG_jll builds libavcodec.so.60, so maybe alsa_plugins_jll needs to be updated to match.
I'm pretty out of touch with how the binary build system works these days, so it may be worth filing an issue on the Yggdrasil repo, they may have a better idea.

I see:
tp@ace7900:~$ ldd /home/tp/.julia/artifacts/d587f48a6815c72dec4b083bf297caec7a8e3f4b/lib/alsa-lib/libasound_module_pcm_a52.so 
	linux-vdso.so.1 (0x00007ffd890e8000)
	libavcodec.so.58 => not found
	libavutil.so.56 => not found
	libavresample.so.4 => not found


Tracing back:

PortAudio.jl Project.toml:
[deps]
alsa_plugins_jll = "5ac2f6bb-493e-5871-9171-112d4c21a6e7"
libportaudio_jll = "2d7b7beb-0762-5160-978e-1ab83a1e8a31"
[compat]
alsa_plugins_jll = "1.2.2"
libportaudio_jll = "19.6.0"

Current alsa_plugins is 1.2.2 which is 3 years old (2021-03-28) https://github.com/JuliaPackaging/Yggdrasil/blob/master/A/alsa_plugins/build_tarballs.jl

Try a clean install with clean depot:

** Try Build
julia> using BinaryBuilder
BinaryBuilder.run_wizard()

https://files.portaudio.com/archives/pa_stable_v190700_20210406.tgz is still the most recent, and that is used in PortAudio https://github.com/JuliaPackaging/Yggdrasil/blob/master/L/libportaudio/build_tarballs.jl

Building from master fails in BinaryBuilder.run_wizard()

** Test blank as test user
tp_test tp

This still fails: (See tp_test_port-audio.org
>tp_test
- [X] install julia:
  https://github.com/JuliaLang/juliaup
    Version 1.10.3 (2024-04-30)
- [X] add PortAudio
  
Precompiling project...
  Progress [=======================================> ]  107/112
  ✗ PortAudio
  111 dependencies successfully precompiled in 50 seconds. 9 already precompiled.
  1 dependency had output during precompilation:
┌ MKL_jll
│   Downloading artifact: MKL
│  
│  [pid 8067] waiting for IO to finish:
│   Handle type        uv_handle_t->data
│   timer              0x1cce390->0x755feb0e6290
│  This means that a package has started a background task or event source that has not finished running. For precompilation to complete successfully, the event source needs to be closed explicitly. See the developer documentation on fixing precompilation hangs for more help.
│  
│  [pid 8067] waiting for IO to finish:
│   Handle type        uv_handle_t->data
│   timer              0x1cce390->0x755feb0e6290
│  This means that a package has started a background task or event source that has not finished running. For precompilation to complete successfully, the event source needs to be closed explicitly. See the developer documentation on fixing precompilation hangs for more help.
└  
  1 dependency errored.
  For a report of the errors see `julia> err`. To retry use `pkg> precompile`

julia> err
PkgPrecompileError: The following 1 direct dependency failed to precompile:

PortAudio [80ea8bcb-4634-5cb3-8ee8-a132660d1d2d]

Failed to precompile PortAudio [80ea8bcb-4634-5cb3-8ee8-a132660d1d2d] to "/home/tp_test/.julia/compiled/v1.10/PortAudio/jl_yy6lXr".
ERROR: LoadError: InitError: could not load library "/home/tp_test/.julia/artifacts/d587f48a6815c72dec4b083bf297caec7a8e3f4b/lib/alsa-lib/libasound_module_pcm_a52.so"
libavcodec.so.58: cannot open shared object file: No such file or directory
Stacktrace:
  [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
    @ Base.Libc.Libdl ./libdl.jl:117
  [2] dlopen(s::String, flags::UInt32)
    @ Base.Libc.Libdl ./libdl.jl:116
  [3] macro expansion
    @ ~/.julia/packages/JLLWrappers/pG9bm/src/products/library_generators.jl:63 [inlined]
  [4] __init__()
    @ alsa_plugins_jll ~/.julia/packages/alsa_plugins_jll/hnVoe/src/wrappers/x86_64-linux-gnu.jl:49
  [5] run_module_init(mod::Module, i::Int64)
    @ Base ./loading.jl:1134
  [6] register_restored_modules(sv::Core.SimpleVector, pkg::Base.PkgId, path::String)
    @ Base ./loading.jl:1122
  [7] _include_from_serialized(pkg::Base.PkgId, path::String, ocachepath::String, depmods::Vector{Any})
    @ Base ./loading.jl:1067
  [8] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String, build_id::UInt128)
    @ Base ./loading.jl:1581
  [9] _require(pkg::Base.PkgId, env::String)
    @ Base ./loading.jl:1938
 [10] __require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1812
 [11] #invoke_in_world#3
    @ ./essentials.jl:926 [inlined]
 [12] invoke_in_world
    @ ./essentials.jl:923 [inlined]
 [13] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1803
 [14] macro expansion
    @ ./loading.jl:1790 [inlined]
 [15] macro expansion
    @ ./lock.jl:267 [inlined]
 [16] __require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1753
 [17] #invoke_in_world#3
    @ ./essentials.jl:926 [inlined]
 [18] invoke_in_world
    @ ./essentials.jl:923 [inlined]
 [19] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1746
 [20] include
    @ ./Base.jl:495 [inlined]
 [21] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
    @ Base ./loading.jl:2222
 [22] top-level scope
    @ stdin:3
during initialization of module alsa_plugins_jll
in expression starting at /home/tp_test/.julia/packages/PortAudio/HNBv4/src/PortAudio.jl:1
in expression starting at stdin:

** [2024-06-08 Sat]
Managed to compile alsa_plugins and make it wrk. See 2024-06-08_fixx-PortAudio/notes.org
** [2024-09-28 Sat]
It works again now, after the merge of JuliaPackaging/Yggdrasil#9105.
Thank you very much @ViralBShah
